import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder, FormControl } from '@angular/forms';
import { RegisterService } from 'src/app/services/register-service/register.service';
import { MessageDialogService } from 'src/app/services/dialog/message-dialog.service';
import { AccountModel } from 'src/app/model/AccountModel';

@Component({
  selector: 'app-add-account',
  templateUrl: './add-account.component.html',
  styleUrls: ['./add-account.component.css']
})
export class AddAccountComponent implements OnInit {

  addForm: FormGroup; 
  account: any;
  constructor(private formBuilder: FormBuilder, private registerService: RegisterService, private dialogService: MessageDialogService) { 
    this.validateForm();
  } 

  ngOnInit(): void {
  }

  validateForm(){
    this.addForm = this.formBuilder.group({ 
      "accountType": new FormControl(),
      "initialValue": new FormControl()
    });
  }
 
  doRegister(){  
    let accountValue: AccountModel = new AccountModel(
      "", //will be generated by server
      this.addForm.controls['accountType'].value,
      this.addForm.controls['initialValue'].value,
      sessionStorage.getItem("userId"),
      "",
      ""
  ); 
     
        this.registerService.createAccount(accountValue).subscribe(
          (success) => {
            this.account = success; 
            let options = {
              title: 'Add Account',
              message1: "Account created successfully!",
              message2: "Account# : "+this.account.accountId,
              cancelText: 'Ok',
              confirmText: 'Ok'
            };
      
            this.dialogService.open(options);
            
            this.dialogService.confirmed().subscribe(confirmed => {
              if (confirmed) {
                  //alert("Jai Ram G ki");
                  //After clicking Ok on message dialog, form should reset
                  this.addForm.reset();
                }
              });
          },
          (err) => {
            let options = {
              title: 'Open Account - error',
              message1: err.error.message,
              message2: "",
              cancelText: 'Ok',
              confirmText: 'Ok'
            };
          }
        );
  }

}
